
server:
  port: 8189

spring:
  application:
    name: admin-client
#  boot:
#    admin:
#      client:
#        url: http://localhost:8188
#\u96C6\u6210eureka
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8181}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
