server:
  port: 8186

spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/

#zuul\u8DEF\u7531\u8F6C\u53D1\u914D\u7F6E\uFF0C/zuul-a/ \u5F00\u5934\u7684\u8BF7\u6C42\u90FD\u8F6C\u53D1\u7ED9ribbon-service\u670D\u52A1\uFF1B\u4EE5/zuul-b/\u5F00\u5934\u7684\u8BF7\u6C42\u90FD\u8F6C\u53D1\u7ED9feign-service\u670D\u52A1
zuul:
  routes:
    zuul-a:
      path: /zuul-a/**
      serviceId: ribbon-service
    zuul-b:
      path: /zuul-b/**
      serviceId: feign-service